# Seleciona a imagem base
FROM grafana/grafana:latest

# Cria os diretórios necessários
RUN mkdir -p /etc/grafana/provisioning/dashboards /etc/grafana/provisioning/datasources

# Copiar os arquivos para o diretório correto
COPY grafana/provisioning/datasource.yml /etc/grafana/provisioning/datasources/
COPY grafana/provisioning/dashboard.yml /etc/grafana/provisioning/dashboards/
COPY grafana/dashboards/mariadb_dashboard.json /etc/grafana/provisioning/dashboards/

# Não há necessidade de mudar as permissões se o Grafana já tiver acesso aos arquivos
USER grafana
