FROM grafana/grafana:latest

USER root

# Criação dos diretórios de provisionamento
RUN mkdir -p /etc/grafana/provisioning/datasources /etc/grafana/provisioning/dashboards

# Copiar os arquivos de provisionamento
COPY provisioning/datasources/datasource.yml /etc/grafana/provisioning/datasources/
COPY provisioning/dashboards/dashboard.yml /etc/grafana/provisioning/dashboards/
COPY dashboards/mariadb_dashboard.json /etc/grafana/provisioning/dashboards/

# Garantir permissões para o usuário grafana
RUN chown -R 472:472 /etc/grafana/provisioning

USER grafana
