FROM grafana/grafana:latest

# Crie os diretórios necessários
RUN mkdir -p /etc/grafana/provisioning/dashboards /etc/grafana/provisioning/datasources

# Copiar os arquivos diretamente, sem usar o chown
COPY provisioning/datasource.yml /etc/grafana/provisioning/datasources/
COPY provisioning/dashboard.yml /etc/grafana/provisioning/dashboards/
COPY dashboards/mariadb_dashboard.json /etc/grafana/provisioning/dashboards/

RUN chown -R 472:472 /var/lib/grafana

USER grafana

