FROM grafana/grafana:latest

USER root

# Certifique-se de que o diretório provisioning/dashboards existe antes de copiá-lo
RUN mkdir /var/lib/grafana/dashboards

# Copiar os arquivos para o diretório correto
COPY provisioning/datasource.yml /etc/grafana/provisioning/datasources/
COPY provisioning/dashboard.yml /etc/grafana/provisioning/dashboards/
COPY dashboards/mariadb_dashboard.json /var/lib/grafana/dashboards/

# Garantir permissões para o usuário grafana
RUN mkdir -p /var/lib/grafana/dashboards && chmod 777 /var/lib/grafana/dashboards



USER grafana